- name: get command output
  shell: |
    journalctl -u edgeware --no-pager > /root/edgeware.log
    tail -n 10000 /root/edgeware.log | grep "Waiting to import block"
  become: yes
  args:
    executable: /bin/bash
  changed_when: False
  register: command_output

- name: result
  debug:
    msg: "Command result: {{ command_output.stdout }}"

- name: remove log
  file:
    path: /root/edgeware.log
    state: absent
