ansibleIntegrationTest: &ansibleIntegrationTest
    docker:
      - image: web3f/secure-validator-ci:v0.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: execute molecule tests for the ansible role at $ROLE_PATH
          command: |
            cd $ROLE_PATH
            molecule test


version: 2

jobs:
  lint:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout

      - run: yarn

      - run:
          name: Run tests
          command: |
            yarn test

  commonIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/common
    <<: *ansibleIntegrationTest

  edgewareCommonIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/edgeware-common
    <<: *ansibleIntegrationTest

  edgewarePublicIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/edgeware-public
    <<: *ansibleIntegrationTest

  edgewareValidatorIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/edgeware-validator
    <<: *ansibleIntegrationTest

  vpnpeerIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/vpnpeer
    <<: *ansibleIntegrationTest

  vpnpeerSetupIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/vpnpeer-setup
    <<: *ansibleIntegrationTest

  edgewareValidatorSessionInfoIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/edgeware-validator-session-info
    <<: *ansibleIntegrationTest

  nodeExporterIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/node-exporter
    <<: *ansibleIntegrationTest

  publishPackage:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout

      - run:
          name: Publish package
          command: npm publish --userconfig=.npmrc-auth

workflows:
  version: 2
  test-deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - commonIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - edgewareCommonIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - edgewarePublicIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - edgewareValidatorIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - edgewareValidatorSessionInfoIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - vpnpeerIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - vpnpeerSetupIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - nodeExporterIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - publishPackage:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - commonIntegrationTest
            - edgewareCommonIntegrationTest
            - edgewarePublicIntegrationTest
            - edgewareValidatorIntegrationTest
            - edgewareValidatorSessionInfoIntegrationTest
            - vpnpeerIntegrationTest
            - vpnpeerSetupIntegrationTest
            - nodeExporterIntegrationTest
