- name: stop edgeware service
  systemd:
    name: edgeware.service
    state: stopped

- name: purge chain
  shell: |
    set -o pipefail
    /usr/local/bin/edgeware purge-chain -y
  become: yes
  become_user: edgeware
  args:
    executable: /bin/bash
  changed_when: False

- name: start edgeware service
  systemd:
    name: edgeware.service
    state: started
